### ISSUE TITLE
homework 3 clearly unfinished

### ISSUE THREAD

**Issue by satuelisa** [Constantino/ComputerVision#1]
why do we bother to have deadlines if you people ignore them? o_0

**Comment by Constantino** [comment]
I tried very hard to accomplish it, and expended more than 12 hours to
understand the way I want it to do. However I couldn't finish.

2015-03-02 8:46 GMT-06:00 satuelisa notifications@github.com:

**Comment by satuelisa** [comment]
Pues, si lo mejoras para cuando califico la tarea 4, echaré un vistazo
nuevamente.

**Comment by satuelisa** [comment]
Lo veré el viernes en la mañana cuando califico lo de agujeros.
